### ISSUE TITLE
Getting error on the NGRORK

### ISSUE THREAD

**Issue by Prottoy2938** [SwayamInSync/clothes-virtual-try-on#13]
I'm following the colab tutorial as described, my ngrok auth token is set up properly as well. But in the very end when  I run the command:

```py
#19
app.run()
``` 

I get this error:

```js
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f49c009f4f0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 440, in send
```

**Comment by OmarGoubail** [comment]
Same thing is happening to me, did you manage to fix it?

**Comment by OmarGoubail** [comment]
@Prottoy2938 I fixed it by accessing the colab terminal and running ngrok http 5000,

**Comment by Prottoy2938** [comment]
I see, great. Could you please share the copy of your colab code?

**Comment by Prottoy2938** [comment]
@OmarGoubail

**Comment by OmarGoubail** [comment]
@Prottoy2938 Code is the same except I deleted run_with_ngrok(app), then I ran ngrok http 5000

**Comment by Prottoy2938** [comment]
@OmarGoubail I'm trying to do the same, but no outcome. Heres a screenshot (is this also what you did?)

https://i.ibb.co/QQpgzjq/Screenshot-356.png

**Comment by Prottoy2938** [comment]
@OmarGoubail  I did made it to work, but the web ui isn't working. When I'm going to the `ngrok url`, its just showing `API is working properly``

**Comment by OmarGoubail** [comment]
@Prottoy2938 Web UI is working on my end, but openpose seems to be running into errors, problem cudnn. @practice404  any idea how to debug?

**Comment by SwayamInSync** [comment]
Dealing with openpose problem here, please check my last comment #19 
Closing this issue.
