### ISSUE TITLE
Google Colab Not working

### ISSUE THREAD

**Issue by Prottoy2938** [SwayamInSync/clothes-virtual-try-on#14]
As the title says. Seems like the google colab code isn't working as expected. `Ngrok` doesn't deploy properly, even with a workaround there seems to be a problem. Issue created [here](https://github.com/practice404/clothes-virtual-try-on/issues/13)

Any fix?

**Comment by sudip550** [comment]
Does colab working??

**Comment by SwayamInSync** [comment]
Closing as of duplicate issue
