### ISSUE TITLE
Issue in generating the output after Setup and running the Client app

### ISSUE THREAD

**Issue by RonakPrasad** [SwayamInSync/clothes-virtual-try-on#16]
### Discussed in https://github.com/practice404/clothes-virtual-try-on/discussions/15

<div type='discussions-op-text'>

<sup>Originally posted by **RonakPrasad** September 19, 2023</sup>
I have followed the Setup.pdf provided in the repo and made the necessary changes required to run the instances in Colab as well as the Client Application on the local machine.

But when I run the Client Application and upload the cloth and model images.
The following errors are thrown: 

In Colab: 
![image](https://github.com/practice404/clothes-virtual-try-on/assets/68803976/25902d3e-f027-4397-b1b5-30507338554c)

In Client App:
![image](https://github.com/practice404/clothes-virtual-try-on/assets/68803976/9dfbafbe-e854-4043-9997-17faca6cdd66)

It would mean a lot if anyone could help with this issue. 

Awaiting your response.

Thank you.

</div>

**Comment by sudip550** [comment]
Hii.... Did you got answer to how to run this on colab successfully

**Comment by MosaabRkia** [comment]
Hi any fix for this issue im getting the same issue?

**Comment by SwayamInSync** [comment]
Dealing issue related to this on #19 
closing it here, please join any conversation there
