### ISSUE TITLE
Copy VTON_HD to your google drive: i. Download the folder from VITON-HD - Google Drive ii. Make sure that all the content is in folder “VITON-HD” iii. Upload this folder to the root of your google drive.

### ISSUE THREAD

**Issue by punithan328** [SwayamInSync/clothes-virtual-try-on#17]
Where is it VTON_HD file . Can u send it

**Comment by sudip550** [comment]
> Where is it VTON_HD file . Can u send it

Heyyy..... Can you please help me to setup this on Google colab

**Comment by practice404** [comment]
@punithan328 it can be found here [VITON-HD](https://drive.google.com/drive/u/2/folders/1rPqxzWj7r7o4whEg_LcAiPnKtcbKFPpe)

**Comment by sudip550** [comment]
> @punithan328 it can be found here [VITON-HD](https://drive.google.com/drive/u/2/folders/1rPqxzWj7r7o4whEg_LcAiPnKtcbKFPpe)

Please help me to use this on colab....

**Comment by punithan328** [comment]
> > @punithan328 it can be found here [VITON-HD](https://drive.google.com/drive/u/2/folders/1rPqxzWj7r7o4whEg_LcAiPnKtcbKFPpe)
> 
> Please help me to use this on colab....



> > @punithan328 it can be found here [VITON-HD](https://drive.google.com/drive/u/2/folders/1rPqxzWj7r7o4whEg_LcAiPnKtcbKFPpe)
> 
> Please help me to use this on colab....

okay sudip ...👍

**Comment by SwayamInSync** [comment]
Closing this issue because of resolved problem
