### ISSUE TITLE
Shifting to Gradio UI

### ISSUE THREAD

**Issue by SwayamInSync** [SwayamInSync/clothes-virtual-try-on#24]
Shift from the current backend and frontend setup to the more clear and concise Gradio application, allowing less confusion in the setup process of server and client.

---
Contributions and suggestions are welcome!

**Comment by vishu002** [comment]
how to run this script , please provide step

**Comment by SwayamInSync** [comment]
@vishu002 check this part of ReadMe file https://github.com/SwayamInSync/clothes-virtual-try-on?tab=readme-ov-file#setup

**Comment by SwayamInSync** [comment]
Resolved in the #25
