### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by JACKzhuz** [SwayamInSync/clothes-virtual-try-on#28]
im a novice ,and i want to run this event,But I don't see the steps file, so I don't know how to run it, I want to run it on the windows cpu, who can you tell me the specific steps

**Comment by SwayamInSync** [comment]
Hey @JACKzhuz just click on the button in readme showing "open in colab" and run all the cells that's it.

It'll take around 30 minutes for setting up everything and then you can upload the images and use it

**Comment by JACKzhuz** [comment]
In the last few steps of my run, I had an issue where the "import gradio as gr" is marked red, indicating that the package is not there
