### ISSUE TITLE
Problem in openpose when trying to run the model F0215 12:27:15.704495 33671 cudnn_conv_layer.cu:21] Check failed: status == CUDNN_STATUS_SUCCESS (8 vs. 0)  

### ISSUE THREAD

**Issue by ayman92011** [SwayamInSync/clothes-virtual-try-on#4]
F0215 12:27:15.704495 33671 cudnn_conv_layer.cu:21] Check failed: status == CUDNN_STATUS_SUCCESS (8 vs. 0)  CUDNN_STATUS_EXECUTION_FAILED
*** Check failure stack trace: ***
    @     0x7f8b64cc01c3  google::LogMessage::Fail()
    @     0x7f8b64cc525b  google::LogMessage::SendToLog()
    @     0x7f8b64cbfebf  google::LogMessage::Flush()
    @     0x7f8b64cc06ef  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f8b64a3adaa  caffe::CuDNNConvolutionLayer<>::Forward_gpu()
    @     0x7f8b649bfba2  caffe::Net<>::ForwardFromTo()
    @     0x7f8b653752d6  op::NetCaffe::forwardPass()
    @     0x7f8b65392232  op::PoseExtractorCaffe::forwardPass()
    @     0x7f8b6538d2eb  op::PoseExtractor::forwardPass()
    @     0x7f8b6538ade0  op::WPoseExtractor<>::work()
    @     0x7f8b653bbb2f  op::Worker<>::checkAndWork()
    @     0x7f8b653bbcbb  op::SubThread<>::workTWorkers()
    @     0x7f8b653c97dd  op::SubThreadQueueInOut<>::work()
    @     0x7f8b653c0841  op::Thread<>::threadFunction()
    @     0x7f8b653c0be5  op::Thread<>::exec()
    @     0x7f8b653c38a4  op::ThreadManager<>::exec()
    @     0x7f8b6541c0c9  op::WrapperT<>::exec()
    @     0x55f2db75320c  openPoseDemo()
    @     0x55f2db74f6c7  main
    @     0x7f8b64d3f083  __libc_start_main
    @     0x55f2db74f6fe  _start

**Comment by SwayamInSync** [comment]
Not sure whether this is the same issue but dealing with openpose issue here #19 
closing it here

**Comment by SwayamInSync** [comment]
After some digging this is occuring because of openpose not working with cuDNN as expected (eating way too much VRAM). I am resolving this issue in #19
