### ISSUE TITLE
NOT ABLE TO GET O/P IMG. INT THE OUTPUT FOLDER ,PROG. IS RUNNING WITHOUT ERROR 

### ISSUE THREAD

**Issue by 24thTinyGiant** [SwayamInSync/clothes-virtual-try-on#7]
I'm not able to get the output image in which the target cloth is pasted on input image of person, the program is giving no error but then also why is the output folder still empty? please Help @practice404  @rao-rohit @Ihtreeek  @Navaneeth-Sharma  PLEASE HELP.

**Comment by PsychoSPooF** [comment]
Yeah Mee to

**Comment by SwayamInSync** [comment]
dealing with openpose issue here #19 
Closing it here
